/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import controller.ApprovalController;
import controller.CetakController;
import javax.swing.JOptionPane;

/**
 *
 * @author Advan Comp
 */
public class FrmApproval extends javax.swing.JInternalFrame {
    private ApprovalController appCtrl = new ApprovalController();
    private String nisnTerpilih = "";
    /**
     * Creates new form FrmApproval
     */
    public FrmApproval() {
        initComponents();
        tblApproval.setModel(appCtrl.getSiapApproval());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCariApproval = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblApproval = new javax.swing.JTable();
        lblNamaSiswa = new javax.swing.JLabel();
        btnApprove = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnCetakSurat = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 153, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Persetujuan Akhir Beasiswa");

        jLabel1.setText("Cari Nama Siswa");

        jLabel2.setText(":");

        tblApproval.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NISN", "Nama Siswa", "Kelas", "Rata-rata Nilai", "Tanggal Verfikasi TU"
            }
        ));
        tblApproval.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblApprovalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblApproval);

        lblNamaSiswa.setText("Nama SIswa");

        btnApprove.setText("SETUJUI");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        btnReject.setText("TOLAK");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        btnRefresh.setText("REFRESH DATA");

        btnCetakSurat.setText("Cetak Surat");
        btnCetakSurat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakSuratActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCariApproval, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblNamaSiswa)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnApprove)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReject)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRefresh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCetakSurat)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtCariApproval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNamaSiswa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApprove)
                    .addComponent(btnReject)
                    .addComponent(btnRefresh)
                    .addComponent(btnCetakSurat))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
         if (nisnTerpilih.equals("")) {
        JOptionPane.showMessageDialog(this, "Silahkan pilih siswa di tabel terlebih dahulu!");
        return;
    }
    
    int confirm = JOptionPane.showConfirmDialog(this, "Setujui beasiswa untuk " + lblNamaSiswa.getText() + "?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        if (appCtrl.approve(nisnTerpilih)) {
            tblApproval.setModel(appCtrl.getSiapApproval());
            nisnTerpilih = ""; // Reset setelah berhasil
            lblNamaSiswa.setText("-");
        }
    }

    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
       if (appCtrl.reject(nisnTerpilih)) {
        tblApproval.setModel(appCtrl.getSiapApproval());
    }
    }//GEN-LAST:event_btnRejectActionPerformed

    private void tblApprovalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblApprovalMouseClicked
         int row = tblApproval.getSelectedRow();
        nisnTerpilih = tblApproval.getValueAt(row, 0).toString();
        lblNamaSiswa.setText(tblApproval.getValueAt(row, 1).toString());
    }//GEN-LAST:event_tblApprovalMouseClicked

    private void btnCetakSuratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakSuratActionPerformed
        if (nisnTerpilih.equals("")) {
            JOptionPane.showMessageDialog(this, "Pilih siswa di tabel dulu!");
        } else {
            CetakController cetak = new CetakController();
            cetak.cetakSuratPengantar(nisnTerpilih);
        }
    }//GEN-LAST:event_btnCetakSuratActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnCetakSurat;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnReject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNamaSiswa;
    private javax.swing.JTable tblApproval;
    private javax.swing.JTextField txtCariApproval;
    // End of variables declaration//GEN-END:variables
}
