/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.CetakController;

/**
 *
 * @author Advan Comp
 */
public class FrmUtama extends javax.swing.JFrame {

    /**
     * Creates new form FrmUtama
     */
    public FrmUtama() {
        initComponents();
        // Agar form muncul persis di tengah layar
        this.setLocationRelativeTo(null); 
        
        // Agar form langsung maximize (layar penuh) saat dibuka
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }
    
    public FrmUtama(String nama, String akses) {
        initComponents();
        
        // Agar form muncul persis di tengah layar
        this.setLocationRelativeTo(null); 
        
        // Agar form langsung maximize (layar penuh) saat dibuka
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        
        // Mengubah label informasi user sesuai data dari FrmLogin
        lblUserAktif.setText("Login Sebagai: " + nama + " (" + akses + ")");
        
        // ---------------------------------------------------------
        // Opsional: Anda bisa mengatur hak akses tombol di sini.
        // Contoh jika login sebagai KEPSEK:
        // if (akses.equalsIgnoreCase("KEPSEK")) {
        //     btnVerifikasi.setEnabled(false); // Kepsek tidak bisa verifikasi
        // }
        // ---------------------------------------------------------
        
        // --- PENGATURAN HAK AKSES TOMBOL ---
    if (akses.equalsIgnoreCase("TU")) {
        // TU tidak boleh approve
        btnApproval.setEnabled(false);
        // Tombol lain aktif
        btnSiswa.setEnabled(true);
        btnVerifikasi.setEnabled(true);
        btnBeasiswa.setEnabled(true); // Ini tombol Pencairan di form kamu
    } 
    else if (akses.equalsIgnoreCase("KEPSEK")) {
        // Kepsek HANYA boleh Approve dan Dashboard
        btnSiswa.setEnabled(false);
        btnVerifikasi.setEnabled(false);
        btnBeasiswa.setEnabled(false); 
        btnApproval.setEnabled(true);
        btnDashboard.setEnabled(true);
        btnBeasiswa.setEnabled(false);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        btnSiswa = new javax.swing.JButton();
        btnBeasiswa = new javax.swing.JButton();
        btnVerifikasi = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblUserAktif = new javax.swing.JLabel();
        btnApproval = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        desktopUtama = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEM INFORMASI BEASISWA");

        panelMenu.setBackground(new java.awt.Color(51, 153, 255));

        btnDashboard.setText("DASHBOARD");
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        btnSiswa.setText("DATA SISWA");
        btnSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiswaActionPerformed(evt);
            }
        });

        btnBeasiswa.setText("DATA BEASISWA");
        btnBeasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeasiswaActionPerformed(evt);
            }
        });

        btnVerifikasi.setText("VERIFIKASI BERKAS");
        btnVerifikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifikasiActionPerformed(evt);
            }
        });

        btnLaporan.setText("LAPORAN");
        btnLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanActionPerformed(evt);
            }
        });

        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblUserAktif.setBackground(new java.awt.Color(255, 255, 255));
        lblUserAktif.setForeground(new java.awt.Color(255, 255, 255));
        lblUserAktif.setText("Login Sebagai: [Nama User]");

        btnApproval.setText("APPROVAL KEPSEK");
        btnApproval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApprovalActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SISTEM INFORMASI");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("BEASISWA/PIP");

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLaporan)
                            .addComponent(btnApproval)
                            .addComponent(btnLogout)
                            .addComponent(btnVerifikasi)
                            .addComponent(btnBeasiswa)
                            .addComponent(btnSiswa)
                            .addComponent(jLabel2)
                            .addGroup(panelMenuLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel3))
                            .addComponent(lblUserAktif)
                            .addComponent(btnDashboard)))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(btnDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnApproval)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSiswa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBeasiswa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVerifikasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLaporan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogout)
                .addGap(30, 30, 30)
                .addComponent(lblUserAktif)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout desktopUtamaLayout = new javax.swing.GroupLayout(desktopUtama);
        desktopUtama.setLayout(desktopUtamaLayout);
        desktopUtamaLayout.setHorizontalGroup(
            desktopUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );
        desktopUtamaLayout.setVerticalGroup(
            desktopUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktopUtama))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(desktopUtama)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerifikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifikasiActionPerformed
        desktopUtama.removeAll();
        desktopUtama.repaint();
        
        FrmVerifikasi fv = new FrmVerifikasi();
        desktopUtama.add(fv);
        fv.setVisible(true);
    }//GEN-LAST:event_btnVerifikasiActionPerformed

    private void btnSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiswaActionPerformed
       // Menghapus semua form yang sedang terbuka agar tidak menumpuk
        desktopUtama.removeAll();
        desktopUtama.repaint();
        
        // Membuka form Siswa
        FrmSiswa fs = new FrmSiswa();
        desktopUtama.add(fs);
        fs.setVisible(true);
    }//GEN-LAST:event_btnSiswaActionPerformed

    private void btnApprovalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApprovalActionPerformed
        desktopUtama.removeAll();
        desktopUtama.repaint();
        
        FrmApproval fa = new FrmApproval();
        desktopUtama.add(fa);
        fa.setVisible(true);
    }//GEN-LAST:event_btnApprovalActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
        desktopUtama.removeAll();
        desktopUtama.repaint();
        
        FrmDashboard fd = new FrmDashboard();
        desktopUtama.add(fd);
        fd.setVisible(true);
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanActionPerformed
        CetakController cetak = new CetakController();
        cetak.cetakLaporanPenerima();
    }//GEN-LAST:event_btnLaporanActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        FrmLogin Login = new FrmLogin();
        Login.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnBeasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeasiswaActionPerformed
        FrmPencairan p = new FrmPencairan();
        desktopUtama.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_btnBeasiswaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApproval;
    private javax.swing.JButton btnBeasiswa;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSiswa;
    private javax.swing.JButton btnVerifikasi;
    private javax.swing.JDesktopPane desktopUtama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblUserAktif;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables
}
