/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import controller.VerifikasiController;

/**
 *
 * @author Advan Comp
 */
public class FrmVerifikasi extends javax.swing.JInternalFrame {
    private VerifikasiController verCtrl = new VerifikasiController();
    private String nisnTerpilih = "";
    
    public FrmVerifikasi() {
        initComponents();
        tblVerifikasi.setModel(verCtrl.getAllUntukVerifikasi());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCariVerifikasi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVerifikasi = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblNamaSiswa = new javax.swing.JLabel();
        chkKK = new javax.swing.JCheckBox();
        chkKTP = new javax.swing.JCheckBox();
        chkAkta = new javax.swing.JCheckBox();
        chkKIP = new javax.swing.JCheckBox();
        btnUpdateStatus = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Verifikasi Berkas & Smart Checklist");

        jLabel1.setText("Cari Siswa");

        jLabel2.setText(":");

        tblVerifikasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NISN", "Nama", "Status Berkas"
            }
        ));
        tblVerifikasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVerifikasiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVerifikasi);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Kelengkapan Berkas"));

        lblNamaSiswa.setText("Nama Siswa");

        chkKK.setText("Fotokopi Kartu Keluarga (KK)");

        chkKTP.setText("Fotokopi KTP Orang Tua");

        chkAkta.setText("Akta Kelahiran");

        chkKIP.setText("Kartu KIP (Opsional)");
        chkKIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkKIPActionPerformed(evt);
            }
        });

        btnUpdateStatus.setText("UPDATE STATUS BERKAS");
        btnUpdateStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkKK)
                    .addComponent(chkKTP)
                    .addComponent(chkAkta)
                    .addComponent(chkKIP)
                    .addComponent(btnUpdateStatus)
                    .addComponent(lblNamaSiswa))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNamaSiswa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkKK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkKTP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkAkta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkKIP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdateStatus)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(txtCariVerifikasi, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCariVerifikasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkKIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkKIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkKIPActionPerformed

    private void tblVerifikasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVerifikasiMouseClicked
     int row = tblVerifikasi.getSelectedRow();
    nisnTerpilih = tblVerifikasi.getValueAt(row, 0).toString();
    lblNamaSiswa.setText(tblVerifikasi.getValueAt(row, 1).toString());
    // Reset semua checkbox
    chkKK.setSelected(false);
    chkKTP.setSelected(false);
    chkAkta.setSelected(false);
    chkKIP.setSelected(false);
    }//GEN-LAST:event_tblVerifikasiMouseClicked

    private void btnUpdateStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStatusActionPerformed
      if (verCtrl.updateStatusBerkas(nisnTerpilih,
            chkKK.isSelected(), chkKTP.isSelected(),
            chkAkta.isSelected(), chkKIP.isSelected())) {
        tblVerifikasi.setModel(verCtrl.getAllUntukVerifikasi());
    }
    }//GEN-LAST:event_btnUpdateStatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdateStatus;
    private javax.swing.JCheckBox chkAkta;
    private javax.swing.JCheckBox chkKIP;
    private javax.swing.JCheckBox chkKK;
    private javax.swing.JCheckBox chkKTP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNamaSiswa;
    private javax.swing.JTable tblVerifikasi;
    private javax.swing.JTextField txtCariVerifikasi;
    // End of variables declaration//GEN-END:variables
}
